# Generated by Django 4.2.6 on 2023-10-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('num_bedroom', models.IntegerField()),
                ('square_footage', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
